
ALTER VIEW [dbo].[VS_CONTRIBUYENTE_CLAVE]
AS
SELECT P.PERSONA AS CONTRIBUYENTE
       , P.NOMBRE_COMPLETO AS NOMBRE
      , CASE WHEN P.NRO_DOC IS NULL THEN CAST(P.PERSONA AS VARCHAR(30))
	         WHEN LEN(LTRIM(RTRIM(P.NRO_DOC))) < 8 THEN  CAST(P.PERSONA AS VARCHAR(30))
			 ELSE LTRIM(RTRIM(P.NRO_DOC)) END AS CLAVE
	  , P.DIRECCION_FISCAL AS DIRECCION
	  , P.EMAIL
	  , P.OBS
	  , P.USUARIO_CREA
	  ,P.F_CREA
	  ,P.USUARIO_MODIFICA
	  ,P.F_MODIFICA
  FROM PERSONA P LEFT OUTER JOIN CONTRIBUYENTE C ON P.PERSONA = C.CONTRIBUYENTE
  --WHERE P.PERSONA = C.CONTRIBUYENTE
GO


