INSERT INTO AREA
SELECT 'NOTARIAS' AS AREA
      ,'NOTARIAS ACCESO A ' AS DESCRIPCION
      ,'PARA ACCESO A CONSULTA DE APTO A CONSTANCIA' AS OBS
      ,'A' AS E
      ,[USUARIO_CREA]
      ,[F_CREA]
      ,[USUARIO_MODIFICA]
      ,[F_MODIFICA]
      ,[UNIDAD]
      ,[SIGLAS]
      ,[GERENCIA]
      ,[SERVIDOR]
      ,[NOMBRE_BASEDATOS]
  FROM AREA
  WHERE AREA = 'RENTAS'

GO

